AWSTemplateFormatVersion: "2010-09-09"
Description: Environment Template Stack

Parameters:
  BucketName1:
    Type: String
    Description: Name of Bucket
    Default: toanla123-env1
  BucketName2:
    Type: String
    Description: Name of Bucket
    Default: toanla123-env2

Resources:
  BucketName1Resource:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref 'BucketName1'
  
  BucketName2Resource:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref 'BucketName2'
